services:
  pathway_db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5552:5432'
    volumes:
      - ./container:/var/lib/postgresql/data
